services:

  ums:
    image: ums-image
    container_name: ums
    env_file:
      - C:/Users/Jagadish.Pannala/UMS/User_Management_System/Backend/.env
    ports:
      - "8000:8000"
    networks:
      - intranet-network

  pms:
    image: ajay1813/pms-image:v1
    container_name: pms
    env_file:
      - C:\Users\Jagadish.Pannala\UMS\.env.pms
    ports:
      - "8080:8080"
    depends_on:
      - ums
    networks:
      - intranet-network

  tms:
    image: 743737183908.dkr.ecr.ap-south-1.amazonaws.com/paves/tms-dev:latest
    container_name: tms
    env_file:
     - C:\Users\Jagadish.Pannala\UMS\.env.tms
    ports:
     - "5000:5000"
    depends_on:
     - ums
    networks:
     - intranet-network

  lms:
    image: swarnaraj08/lms:latest
    container_name: lms
    env_file:
     - C:\Users\Jagadish.Pannala\UMS\.env.lms
    ports:
      - "9999:9999"
    depends_on:
     - ums
    networks:
     - intranet-network


networks:
  intranet-network:
    driver: bridge